apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "java-prototype.fullname" . }}"
  labels:
    app: {{ template "java-prototype.name" . }}
    chart: {{ template "java-prototype.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ if .Values.mysql.enabled }}
  JAVAPROTOTYPE_MYSQL_CONNECTION_PASS: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
{{ else }}
  JAVAPROTOTYPE_MYSQL_CONNECTION_PASS: {{ .Values.mysqlPassword | b64enc | quote }}
  FLYWAY_PASSWORD: {{ .Values.flywayPass | b64enc | quote }}
{{ end }}
