version: '3.1'
services:
  mysql:
    image: mysql:5.7.21
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: java_prototype
      MYSQL_PASSWORD: java_prototype
    ports:
      - "3306:3306"
