apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: sysbench-1
  name: sysbench-1
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: sysbench-prepare
        image: severalnines/sysbench
        command:
        - sysbench
        - --db-driver=mysql
        - --report-interval=2
        - --mysql-table-engine=innodb
        - --oltp-table-size=100000
        - --oltp-tables-count=4
        - --threads=4
        - --mysql-host=old-mysql
        - --mysql-port=3306
        - --mysql-user=root
        - --mysql-password=not-a-secure-password
        - /usr/share/sysbench/tests/include/oltp_legacy/oltp.lua
        - prepare
